SchoolLocker.Web/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SchoolLocker.Web.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

SchoolLocker.Web/Pages/Bookings/Create.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SchoolLocker.Core.Contracts;
using SchoolLocker.Core.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolLocker.Web.Pages.Bookings
{
    public class LockerBookingModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public Booking Booking { get; set; }

        [BindProperty]
        public string CurrentUsersName { get; set; }

        public LockerBookingModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult OnGetAsync(int id)
        {
            // TODO: Daten initialisieren
            return Page();
        }

        public async Task<IActionResult> OnPostCreateAsync()
        {
            if (ModelState.IsValid)
            {
                var pupil = await _unitOfWork
                    .PupilRepository
                    .GetByIdAsync(Booking.PupilId);
                if (pupil == null)
                {
                    return NotFound();
                }

                var locker = await _unitOfWork
                    .LockerRepository
                    .GetByIdAsync(Booking.LockerId);

                if (locker == null)
                {
                    return NotFound();
                }

                Booking newBooking = new()
                {
                    LockerId = locker.Id,
                    PupilId = pupil.Id,
                    From = Booking.From,
                    To = Booking.To
                };

                await _unitOfWork.BookingRepository.AddAsync(newBooking);
                try
                {
                    await _unitOfWork.SaveChangesAsync();
                    return RedirectToPage("./Index");
                }
                catch (ValidationException validationException)
                {
                    ValidationResult valResult = validationException.ValidationResult;
                    ModelState.AddModelError("", valResult.ErrorMessage);
                }
            }

            return Page();
        }
    }
}

SchoolLocker.Web/Pages/Bookings/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SchoolLocker.Core.Contracts;
using SchoolLocker.Core.DataTransferObjects;
using SchoolLocker.Core.Entities;

namespace SchoolLocker.Web.Pages.Bookings
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public SchoolLockerOverviewDto[] SchoolLockerOverviewDtos { get; set; }
        public BookingDto[] Bookings { get; set; }

        public async Task OnGetAsync()
        {
            SchoolLockerOverviewDtos = await _unitOfWork.LockerRepository.GetLockersOverviewAsync();

            // TODO: eigene Buchungen laden
            // var pupil = await _userManager.GetUserAsync(HttpContext.User);
            // ...
        }
    }
}

SchoolLocker.Web/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SchoolLocker.Web.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

SchoolLocker.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SchoolLocker.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

SchoolLocker.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using SchoolLocker.Core.Contracts;
using SchoolLocker.Core.DataTransferObjects;
using System.Threading.Tasks;

namespace SchoolLocker.Web.Pages
{
    public class IndexModel : PageModel
    {
    }
}

SchoolLocker.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SchoolLocker.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SchoolLocker.Web/Pages/Pupils/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SchoolLocker.Core.Contracts;
using SchoolLocker.Core.Entities;
using System.Threading.Tasks;

namespace SchoolLocker.Web.Pages.Pupils
{
    [Authorize(Roles = "Admin")]
    public class DetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public DetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public Pupil Pupil { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Pupil = await _unitOfWork.PupilRepository.GetByIdAsync(id.Value);

            if (Pupil == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

SchoolLocker.Web/Pages/Pupils/Edit.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SchoolLocker.Core.Contracts;
using SchoolLocker.Core.Entities;
using SchoolLocker.Web.DataTransferObjects;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace SchoolLocker.Web.Pages.Pupils
{
    public class EditModel : PageModel
    {
        private readonly UserManager<Pupil> _userManager;

        public EditModel(UserManager<Pupil> userManager)
        {
            _userManager = userManager;
        }

        [BindProperty]
        public PupilWithDetailsDto Pupil { get; set; }

        public IActionResult OnGetAsync(int id)
        {
            return Page();
        }

        public IActionResult OnPostAsync()
        {
            // TODO

            return RedirectToPage("./Index");
        }
    }
}

SchoolLocker.Web/Pages/Pupils/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SchoolLocker.Core.Contracts;
using SchoolLocker.Core.Entities;
using SchoolLocker.Web.DataTransferObjects;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace SchoolLocker.Web.Pages.Pupils
{
    public class IndexModel : PageModel
    {
        public PupilWithDetailsDto[] Pupils { get; set; }

        public ActionResult OnGetAsync()
        {
            return Page();
        }
    }
}

SchoolLocker.Web/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

SchoolLocker.Web/Pages/Bookings/Create.cshtml
@page
@model SchoolLocker.Web.Pages.Bookings.LockerBookingModel
@{
    ViewData["Title"] = "Locker Booking";
}

<h2>Create Booking</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">

            <div class="form-group">
                <label asp-for="Booking.Locker.Number" class="control-label"></label>
                <input asp-for="Booking.Locker.Number" class="form-control" readonly="readonly" />
            </div>
            <div class="form-group">
                <label asp-for="Booking.PupilId" class="control-label"></label>
                <input asp-for="CurrentUsersName" class="form-control" readonly="readonly" />
            </div>
            <div class="form-group">
                <label asp-for="Booking.From" class="control-label"></label>
                <input asp-for="Booking.From" class="form-control" type="date" />
                <span asp-validation-for="Booking.From" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Booking.To" class="control-label"></label>
                <input asp-for="Booking.To" class="form-control" type="date" />
                <span asp-validation-for="Booking.To" class="text-danger"></span>
            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Booking.LockerId" type="hidden" />
            <input asp-for="Booking.PupilId" type="hidden" />

            <div class="form-group">
                <input type="submit"
                       value="Add Booking"
                       class="btn btn-default"
                       asp-page-handler="Create" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="/Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolLocker.Web/Pages/Bookings/Index.cshtml
@page
@model SchoolLocker.Web.Pages.Bookings.IndexModel
@{
    ViewData["Title"] = "Lockers Overview";
}

<h2>Lockers Overview</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th class="text-center col-md-1">
                @Html.DisplayNameFor(model => model.SchoolLockerOverviewDtos[0].Locker.Number)
            </th>
            <th class="text-center col-md-1">
                @Html.DisplayNameFor(model => model.SchoolLockerOverviewDtos[0].CountBookings)
            </th>
            <th class="text-center col-md-2">
                @Html.DisplayNameFor(model => model.SchoolLockerOverviewDtos[0].From)
            </th>
            <th class="text-center col-md-2">
                @Html.DisplayNameFor(model => model.SchoolLockerOverviewDtos[0].To)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.SchoolLockerOverviewDtos)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Locker.Number)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.CountBookings)
                </td>
                <td class="text-center">
                    @if (item.From != null)
                    {
                        @item.From.Value.ToShortDateString()
                    }
                </td>
                <td class="text-center">
                    @if (item.To != null)
                    {
                        @item.To.Value.ToShortDateString()
                    }
                </td>
                <td><a asp-page="/Bookings/Create" asp-route-id="@item.Locker.Id">Book</a></td>
            </tr>
        }
    </tbody>
</table>

<h2>My Bookins</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th class="text-center col-md-1">
                @Html.DisplayNameFor(model => model.Bookings[0].LockerNumber)
            </th>
            <th class="text-center col-md-2">
                @Html.DisplayNameFor(model => model.Bookings[0].From)
            </th>
            <th class="text-center col-md-2">
                @Html.DisplayNameFor(model => model.Bookings[0].To)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Bookings)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.LockerNumber)
                </td>
                <td class="text-center">
                    @item.From.ToShortDateString()
                </td>
                <td class="text-center">
                    @if (item.To != null)
                    {
                        @item.To.Value.ToShortDateString();
                    }
                </td>

            </tr>
        }
    </tbody>
</table>

SchoolLocker.Web/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SchoolLocker.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "School Locker";
}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">School Locker</h1>
        <p class="lead">Lets you manage all the lockers in your school.</p>
    </div>
</div>

SchoolLocker.Web/Pages/Pupils/Details.cshtml
@page
@model SchoolLocker.Web.Pages.Pupils.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Pupil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Pupil.Firstname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pupil.Firstname)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pupil.Lastname)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pupil.Lastname)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Pupil.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

SchoolLocker.Web/Pages/Pupils/Edit.cshtml
@page
@model SchoolLocker.Web.Pages.Pupils.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Pupil</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Pupil.Id" class="control-label"></label>
                <input asp-for="Pupil.Id" class="form-control" readonly />
                <span asp-validation-for="Pupil.Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pupil.Username" class="control-label"></label>
                <input asp-for="Pupil.Username" class="form-control" readonly />
                <span asp-validation-for="Pupil.Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pupil.Firstname" class="control-label"></label>
                <input asp-for="Pupil.Firstname" class="form-control" />
                <span asp-validation-for="Pupil.Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pupil.Lastname" class="control-label"></label>
                <input asp-for="Pupil.Lastname" class="form-control" />
                <span asp-validation-for="Pupil.Lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pupil.IsAdmin" class="control-label"></label>
                <input asp-for="Pupil.IsAdmin" class="form-control" />
                <span asp-validation-for="Pupil.IsAdmin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="Pupil.Id" />
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SchoolLocker.Web/Pages/Pupils/Index.cshtml
@page
@model SchoolLocker.Web.Pages.Pupils.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<table class="table">
    <thead>
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Pupils[0].Lastname)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Pupils[0].Firstname)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Pupils[0].Username)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Pupils[0].IsAdmin)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Pupils[0].RegisteredSince)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Pupils)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Lastname)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Firstname)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.IsAdmin)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.RegisteredSince)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SchoolLocker.Web/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using SchoolLocker.Core.Entities;
@inject SignInManager<Pupil> SignInManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolLocker.WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">SchoolLocker.WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Pupils/Index">Pupils</a></li>
                    <li><a asp-page="/Bookings/Index">Bookings</a></li>
                    <li><a href="/swagger">API</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item center-block">
                            <form method="post" asp-page="/Auth/Logout">
                                <button type="submit" class="btn btn-link" style="margin-top: 8px">Logout (@User.Identity.Name)</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li><a asp-page="/Auth/Login">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020/21 - SchoolLocker.WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>